name: Deploy

# Trigger the workflow on push and pull request events on the main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"
# Authenticate to the server via ssh and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ~/web-dev-quiz-competition-next
            chmod +x ./.scripts/deploy.sh
            ./.scripts/deploy.sh
  call-daily-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call the Next.js API
        run: |
          curl -X POST https://webdevquiz.online/api/archiveUsers
